
development:
  adapter: postgresql
  encoding: utf8
  database: list_app_dev
  pool: 5
  username: seanmcmahon
  password: 

test:
  adapter: postgresql
  encoding: utf8
  database: list_api_test
  pool: 5
  username: seanmcmahon
  password:

