
development:
  adapter: postgresql
  encoding: unicode
  database: list_app_dev
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: list_api_test
  pool: 5
  username: 
  password:

